document.write("");
document.write("<div class=\"sidebar-nav\">");
document.write("    <ul>");
document.write("        <li><a href=\"addEngineer.html\" class=\"nav-header\"><i class=\"fa fa-fw fa-circle\"><\/i> 输入工程师资料<\/a><\/li>");
document.write("        <li><a href=\"#\" data-target=\".delete-menu\" class=\"nav-header collapsed\" data-toggle=\"collapse\">");
document.write("            <i class=\"fa fa-fw fa-circle\"><\/i> 删除指定工程师资料<i class=\"fa fa-collapse\"><\/i><\/a>");
document.write("        <li>");
document.write("            <ul class=\"delete-menu nav nav-list collapse\">");
document.write("                <li ><a href=\"deleteEngineerById.html\"><span class=\"fa fa-caret-right\"><\/span> 按编号删除<\/a><\/li>");
document.write("                <li ><a href=\"deleteEngineerByName.html\"><span class=\"fa fa-caret-right\"><\/span> 按姓名删除<\/a><\/li>");
document.write("            <\/ul>");
document.write("        <\/li>");
document.write("        <li><a href=\"#\" data-target=\".alter-menu\" class=\"nav-header collapsed\" data-toggle=\"collapse\">");
document.write("            <i class=\"fa fa-fw fa-circle\"><\/i> 修改指定工程师资料<i class=\"fa fa-collapse\"><\/i><\/a>");
document.write("        <li>");
document.write("            <ul class=\"alter-menu nav nav-list collapse\">");
document.write("                <li ><a href=\"alterEngineerById.html\"><span class=\"fa fa-caret-right\"><\/span> 按编号修改<\/a><\/li>");
document.write("                <li ><a href=\"alterEngineerByName.html\"><span class=\"fa fa-caret-right\"><\/span> 按姓名修改<\/a><\/li>");
document.write("            <\/ul>");
document.write("        <\/li>");
document.write("        <li><a href=\"#\" data-target=\".query-menu\" class=\"nav-header collapsed\" data-toggle=\"collapse\">");
document.write("            <i class=\"fa fa-fw fa-circle\"><\/i> 查询指定工程师资料<i class=\"fa fa-collapse\"><\/i><\/a>");
document.write("        <li>");
document.write("            <ul class=\"query-menu nav nav-list collapse\">");
document.write("                <li ><a href=\"searchEngineerById.html\"><span class=\"fa fa-caret-right\"><\/span> 按编号查询<\/a><\/li>");
document.write("                <li ><a href=\"searchEngineerByName.html\"><span class=\"fa fa-caret-right\"><\/span> 按姓名查询<\/a><\/li>");
document.write("            <\/ul>");
document.write("        <\/li>");
document.write("        <li><a href=\"calculateEngineerSalary.html\" class=\"nav-header\"><i class=\"fa fa-fw fa-circle\"><\/i> 计算工程师月薪水<\/a><\/li>");
document.write("        <li><a href=\"sortEngineer.html\" class=\"nav-header\"><i class=\"fa fa-fw fa-circle\"><\/i> 对工程师资料进行排序<\/a><\/li>");
document.write("        <li><a href=\"clearAllEngineer.html\" class=\"nav-header\"><i class=\"fa fa-fw fa-circle\"><\/i> 清空所有工程师资料<\/a><\/li>");
document.write("        <li><a href=\"printEngineerInfo.html\" class=\"nav-header\"><i class=\"fa fa-fw fa-circle\"><\/i> 打印工程师资料信息报表<\/a><\/li>");
document.write("        ");
document.write("    <\/ul>");
document.write("<\/div>");
