document.write("");
document.write("<div class=\"navbar navbar-default\" role=\"navigation\">");
document.write("    <div class=\"navbar-header\">");
document.write("        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.write("            <span class=\"sr-only\">Toggle navigation<\/span>");
document.write("            <span class=\"icon-bar\"><\/span>");
document.write("            <span class=\"icon-bar\"><\/span>");
document.write("            <span class=\"icon-bar\"><\/span>");
document.write("        <\/button>");
document.write("        <a class=\"\" href=\"index.html\"><span class=\"navbar-brand\"><span class=\"fa fa-paper-plane\"><\/span> 人事部系统<\/span><\/a><\/div>");
document.write("");
document.write("    <div class=\"navbar-collapse collapse\" style=\"height: 1px;\">");
document.write("        <ul id=\"main-menu\" class=\"nav navbar-nav navbar-right\">");
document.write("            <li class=\"dropdown hidden-xs\">");
document.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
document.write("                    <span class=\"glyphicon glyphicon-user padding-right-small\" style=\"position:relative;top: 3px;\"><\/span> ");
document.write("					<div id=\"n_r\" class=\"sty\"><\/div> <style>.sty{display:inline-block;}<\/style>");
document.write("                    <i class=\"fa fa-caret-down\"><\/i>");
document.write("                <\/a>");
document.write("");
document.write("                <ul class=\"dropdown-menu\">");
document.write("                    <li><a tabindex=\"-1\" href=\"loginUser.html\">退出登录<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/li>");
document.write("        <\/ul>");
document.write("");
document.write("    <\/div>");
document.write("<\/div>");
