document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'\'>");
document.writeln("");
document.writeln("    <link href=\'http://fonts.googleapis.com/css?family=Open+Sans:400,700\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'lib/bootstrap/css/bootstrap.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'lib/font-awesome/css/font-awesome.css\'>");
document.writeln("");
document.writeln("    <script src=\'lib/jquery-1.11.1.min.js\' type=\'text/javascript\'></script>");
document.writeln("	<script src=\'//cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js\'></script>");
document.writeln("    <script src=\'lib/jQuery-Knob/js/jquery.knob.js\' type=\'text/javascript\'></script>");
document.writeln("    <script type=\'text/javascript\'>");
document.writeln("        $(function() {");
document.writeln("            $(\'.knob\').knob();");
document.writeln("        });");
document.writeln("    </script>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'stylesheets/theme.css\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'stylesheets/premium.css\'>");