document.write("<!-- Demo page code -->");
document.write("");
document.write("<script type=\"text\/javascript\">");
document.write("    $(function() {");
document.write("        var match = document.cookie.match(new RegExp('color=([^;]+)'));");
document.write("        if(match) var color = match[1];");
document.write("        if(color) {");
document.write("            $('body').removeClass(function (index, css) {");
document.write("                return (css.match (\/\btheme-\S+\/g) || []).join(' ')");
document.write("            })");
document.write("            $('body').addClass('theme-' + color);");
document.write("        }");
document.write("");
document.write("        $('[data-popover=\"true\"]').popover({html: true});");
document.write("");
document.write("    });");
document.write("<\/script>");
document.write("<style type=\"text\/css\">");
document.write("    #line-chart {");
document.write("        height:300px;");
document.write("        width:800px;");
document.write("        margin: 0px auto;");
document.write("        margin-top: 1em;");
document.write("    }");
document.write("    .navbar-default .navbar-brand, .navbar-default .navbar-brand:hover {");
document.write("        color: #fff;");
document.write("    }");
document.write("<\/style>");
document.write("");
document.write("<script type=\"text\/javascript\">");
document.write("    $(function() {");
document.write("        var uls = $('.sidebar-nav > ul > *').clone();");
document.write("        uls.addClass('visible-xs');");
document.write("        $('#main-menu').append(uls.clone());");
document.write("    });");
document.write("<\/script>");
document.write("");
document.write("<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->");
document.write("<!--[if lt IE 9]>");
document.write("<script src=\"http:\/\/html5shim.googlecode.com\/svn\/trunk\/html5.js\"><\/script>");
document.write("<![endif]-->");
document.write("");
document.write("<!-- Le fav and touch icons -->");
document.write("<link rel=\"shortcut icon\" href=\"..\/assets\/ico\/favicon.ico\">");
document.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"..\/assets\/ico\/apple-touch-icon-144-precomposed.png\">");
document.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"..\/assets\/ico\/apple-touch-icon-114-precomposed.png\">");
document.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"..\/assets\/ico\/apple-touch-icon-72-precomposed.png\">");
document.write("<link rel=\"apple-touch-icon-precomposed\" href=\"..\/assets\/ico\/apple-touch-icon-57-precomposed.png\">");
document.write("");
document.write("");
document.write("<!--[if lt IE 7 ]> <body class=\"ie ie6\"> <![endif]-->");
document.write("<!--[if IE 7 ]> <body class=\"ie ie7 \"> <![endif]-->");
document.write("<!--[if IE 8 ]> <body class=\"ie ie8 \"> <![endif]-->");
document.write("<!--[if IE 9 ]> <body class=\"ie ie9 \"> <![endif]-->");
document.write("<!--[if (gt IE 9)|!(IE)]><!-->");
document.write("");
document.write("<!--<![endif]-->");
